// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OfficesLegal.Infra.Data.EF;

namespace OfficesLegal.Infra.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("OfficesLegal.Domain.ProcessCases.ProcessCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_PROCESS_CASE")
                        .HasComment("Primary key table")
                        .UseIdentityColumn();

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CASE_NUMBER")
                        .HasComment("that represents the case number according to the National Council of Justice\r\n                            (CNJ) standard.It has the format: NNNNNNN - NN.NNNN.N.NN.NNNN, where N can be any positive\r\n                            integer");

                    b.Property<string>("CourtName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("COURT_NAME")
                        .HasComment("that represents the name of the court of origin of the case. Example: Supreme\r\n                          Federal Court.\r\n                         ");

                    b.Property<string>("NameOfTheResponsible")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME_OF_THE_RESPONSIBLE")
                        .HasComment("representing the name of the lawyer responsible for the case.");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("REGISTRATION_DATE")
                        .HasComment("Date on which the case was registered in the system.");

                    b.HasKey("Id");

                    b.ToTable("TB_PROCESS_CASE");
                });
#pragma warning restore 612, 618
        }
    }
}
